
            #include <cassert>
            #include <stdlib.h>
            #include <cuda.h>
            #include "common.h"
            

            
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[36];
  __shared__ float pad_temp_shared[2320];
  __shared__ float kernel_shared[144];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  compute_local[(8)] = 0.000000e+00f;
  compute_local[(9)] = 0.000000e+00f;
  compute_local[(10)] = 0.000000e+00f;
  compute_local[(11)] = 0.000000e+00f;
  compute_local[(12)] = 0.000000e+00f;
  compute_local[(13)] = 0.000000e+00f;
  compute_local[(14)] = 0.000000e+00f;
  compute_local[(15)] = 0.000000e+00f;
  compute_local[(16)] = 0.000000e+00f;
  compute_local[(17)] = 0.000000e+00f;
  compute_local[(18)] = 0.000000e+00f;
  compute_local[(19)] = 0.000000e+00f;
  compute_local[(20)] = 0.000000e+00f;
  compute_local[(21)] = 0.000000e+00f;
  compute_local[(22)] = 0.000000e+00f;
  compute_local[(23)] = 0.000000e+00f;
  compute_local[(24)] = 0.000000e+00f;
  compute_local[(25)] = 0.000000e+00f;
  compute_local[(26)] = 0.000000e+00f;
  compute_local[(27)] = 0.000000e+00f;
  compute_local[(28)] = 0.000000e+00f;
  compute_local[(29)] = 0.000000e+00f;
  compute_local[(30)] = 0.000000e+00f;
  compute_local[(31)] = 0.000000e+00f;
  compute_local[(32)] = 0.000000e+00f;
  compute_local[(33)] = 0.000000e+00f;
  compute_local[(34)] = 0.000000e+00f;
  compute_local[(35)] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 16; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[((((int)threadIdx.x) * 2))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((int)threadIdx.x) / 10) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + ((((int)threadIdx.x) % 10) * 2)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 1) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 1) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 108))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 108) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 8) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 109))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 109) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 9) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 216))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 216) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 16) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 217))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 217) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 17) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 324))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 324) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 4) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 325))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 325) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 5) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 432))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 432) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 12) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 433))] = data[((((((rc_outer_outer * 12544) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 433) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 13) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 540))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 540) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + (((((((int)threadIdx.x) * 2) + 540) % 580) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + ((((int)threadIdx.x) % 10) * 2)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 541))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 541) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + (((((((int)threadIdx.x) * 2) + 541) % 580) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 1) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 648))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 648) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 68) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 8) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 649))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 649) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 69) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 9) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 756))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 756) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 176) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 16) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 757))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 757) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 177) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 17) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 864))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 864) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 284) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 4) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 865))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 865) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 285) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 5) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 972))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 972) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 392) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 12) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 973))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 973) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 393) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 13) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1080))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1080) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + (((((((int)threadIdx.x) * 2) + 500) % 580) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + ((((int)threadIdx.x) % 10) * 2)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1081))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1081) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + (((((((int)threadIdx.x) * 2) + 501) % 580) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 1) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1188))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1188) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 28) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 8) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1189))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1189) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 29) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 9) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1296))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1296) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 136) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 16) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1297))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1297) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 137) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 17) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1404))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1404) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 244) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 4) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1405))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1405) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 245) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 5) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1512))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1512) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 352) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 12) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1513))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1513) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 353) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 13) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1620))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1620) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 460) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + ((((int)threadIdx.x) % 10) * 2)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1621))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1621) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 461) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 1) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1728))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1728) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + (((((((int)threadIdx.x) * 2) + 568) % 580) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 8) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1729))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1729) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + (((((((int)threadIdx.x) * 2) + 569) % 580) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 9) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1836))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1836) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 96) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 16) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1837))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1837) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 97) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 17) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1944))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1944) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 204) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 4) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1945))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 1945) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 205) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 5) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 2052))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 2052) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 312) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 12) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 2053))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 2053) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 313) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 13) % 20)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 2160))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 2160) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 420) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + ((((int)threadIdx.x) % 10) * 2)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 2161))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 2161) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 421) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 1) % 20)))];
    if (((int)threadIdx.x) < 26) {
      pad_temp_shared[(((((int)threadIdx.x) * 2) + 2268))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 2268) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 528) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 8) % 20)))];
    }
    if (((int)threadIdx.x) < 26) {
      pad_temp_shared[(((((int)threadIdx.x) * 2) + 2269))] = data[(((((((rc_outer_outer * 12544) + ((((((int)threadIdx.x) * 2) + 2269) / 580) * 3136)) + (((((int)blockIdx.x) % 6) / 3) * 1512)) + ((((((int)threadIdx.x) * 2) + 529) / 20) * 56)) + ((((int)blockIdx.x) % 3) * 18)) + (((((int)threadIdx.x) * 2) + 9) % 20)))];
    }
    kernel_shared[(((int)threadIdx.x))] = kernel[((((((((int)blockIdx.x) / 6) * 2304) + ((((int)threadIdx.x) / 36) * 576)) + (rc_outer_outer * 36)) + (((int)threadIdx.x) % 36)))];
    kernel_shared[((((int)threadIdx.x) + 54))] = kernel[(((((((((int)blockIdx.x) / 6) * 2304) + (((((int)threadIdx.x) + 54) / 36) * 576)) + (rc_outer_outer * 36)) + ((((((int)threadIdx.x) / 9) + 2) & 3) * 9)) + (((int)threadIdx.x) % 9)))];
    if (((int)threadIdx.x) < 36) {
      kernel_shared[((((int)threadIdx.x) + 108))] = kernel[((((((((int)blockIdx.x) / 6) * 2304) + (rc_outer_outer * 36)) + ((int)threadIdx.x)) + 1728))];
    }
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 2; ++rc_outer_inner) {
      for (int ry_outer_inner = 0; ry_outer_inner < 3; ++ry_outer_inner) {
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 1))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 3))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 4))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 5))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 20))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 21))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 22))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 23))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 24))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 25))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 40))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 41))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 42))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 43))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 44))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 45))] * kernel_shared[(((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)))]));
        compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[(((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 1))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 2))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 3))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 4))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 5))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 20))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 21))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 22))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 23))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 24))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 25))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 40))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 41))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 42))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 43))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 44))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 45))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 36))]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 580))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 581))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 582))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 583))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 584))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 585))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 600))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 601))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 602))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 603))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 604))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 605))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 620))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 621))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 622))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 623))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 624))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 625))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 9))]));
        compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 580))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 581))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 582))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 583))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 584))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 585))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 600))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 601))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 602))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 603))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 604))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 605))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 620))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 621))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 622))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 623))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 624))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 625))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 45))]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 1))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 2))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 3))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 4))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 5))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 6))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 21))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 22))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 23))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 24))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 25))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 26))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 41))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 42))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 43))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 44))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 45))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 46))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 1))]));
        compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 1))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 2))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 3))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 4))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 5))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 6))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 21))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 22))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 23))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 24))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 25))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 26))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 41))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 42))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 43))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 44))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 45))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 46))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 37))]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 581))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 582))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 583))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 584))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 585))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 586))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 601))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 602))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 603))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 604))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 605))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 606))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 621))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 622))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 623))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 624))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 625))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 626))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 10))]));
        compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 581))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 582))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 583))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 584))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 585))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 586))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 601))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 602))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 603))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 604))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 605))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 606))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 621))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 622))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 623))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 624))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 625))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 626))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 46))]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 2))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 3))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 4))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 5))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 6))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 7))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 22))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 23))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 24))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 25))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 26))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 27))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 42))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 43))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 44))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 45))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 46))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 47))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 2))]));
        compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 2))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 3))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 4))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 5))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 6))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 7))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 22))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 23))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 24))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 25))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 26))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 27))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 42))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 43))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 44))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 45))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 46))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 47))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 38))]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 582))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 583))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 584))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 585))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 586))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 587))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 602))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 603))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 604))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 605))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 606))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 607))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 622))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 623))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 624))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 625))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 626))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 627))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 11))]));
        compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 582))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 583))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 584))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 585))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 586))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 587))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 602))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 603))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 604))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 605))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 606))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 607))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 622))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 623))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 624))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 625))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 626))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
        compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((((rc_outer_inner * 1160) + (((((int)threadIdx.x) % 27) / 3) * 60)) + (ry_outer_inner * 20)) + ((((int)threadIdx.x) % 3) * 6)) + 627))] * kernel_shared[((((((((int)threadIdx.x) / 27) * 72) + (rc_outer_inner * 18)) + (ry_outer_inner * 3)) + 47))]));
      }
    }
  }
  for (int ff_inner = 0; ff_inner < 2; ++ff_inner) {
    for (int yy_inner = 0; yy_inner < 3; ++yy_inner) {
      for (int xx_inner = 0; xx_inner < 6; ++xx_inner) {
        compute[(((((((((((((int)blockIdx.x) / 6) * 11664) + ((((int)threadIdx.x) / 27) * 5832)) + (ff_inner * 2916)) + (((((int)blockIdx.x) % 6) / 3) * 1458)) + (((((int)threadIdx.x) % 27) / 3) * 162)) + (yy_inner * 54)) + ((((int)blockIdx.x) % 3) * 18)) + ((((int)threadIdx.x) % 3) * 6)) + xx_inner))] = compute_local[((((ff_inner * 18) + (yy_inner * 6)) + xx_inner))];
      }
    }
  }
}



void conv_kernel_wrapper(int N_B, int N_C, int N_H, int N_W, int N_F, int N_R, int N_S, int PaddingH, int PaddingW,
                        int StrideH, int StrideW, int N_X, int N_Y, const float *Input, 
                        const float *Kernel, float *Output, int itr) {
                        cudaEvent_t start;
                        CHECK(cudaEventCreate(&start));
                        cudaEvent_t stop;
                        CHECK(cudaEventCreate(&stop));
                        float *dev_Input;
                        float *dev_Kernel;
                        float *dev_Output;
                    
                        CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                        CHECK(cudaMemcpy(dev_Kernel, Kernel, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                        CHECK(cudaMemcpy(dev_Input, Input, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Output, sizeof(float) * N_B * N_F * N_Y * N_X));
                        CHECK(cudaMemset(dev_Output, 0, sizeof(float) * N_B * N_F * N_Y * N_X));
                    
dim3 size_grid(96,1,1);

dim3 size_block(54,1,1);
 
                       printf("warmup....\n");
                        default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                    
                        double *time_arr = (double *)malloc(itr * sizeof(double));
                        for (int j = 1; j < itr; j++) {
                            CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                            CHECK(cudaMemcpy(dev_Kernel, Kernel+j*N_F * N_C * N_R * N_S, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                            CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                            CHECK(cudaMemcpy(dev_Input, Input+j*N_B * N_C * N_H * N_W, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                            /* Record the start event*/
                            CHECK(cudaEventRecord(start, NULL));
                            default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                            /* Record the end event */
                            CHECK(cudaEventRecord(stop, NULL));
                            /* Wait for the stop event to complete*/
                            CHECK(cudaEventSynchronize(stop));
                            float msec = 0.0f;
                            cudaEventElapsedTime(&msec, start, stop);
                            time_arr[j] = msec;
                        }
                    
                       
                    
                        //cudaError_t err = cudaGetLastError();
                        //if (err != cudaSuccess) printf("Error: %s\n", cudaGetErrorString(err));
                        double msecTotal = 0;
                        for (int j = 1; j < itr; j++) {   
                            printf("%0.5lf\n", time_arr[j]);
                            msecTotal += time_arr[j];
                        }
                    
                        double msecPerMatrixMul = (msecTotal) / itr;
                        double flopsPerMatrixMul = 2.0 * N_B * N_C * N_X * N_Y * N_F * N_R * N_S;
                    
                        double gigaFlops = (flopsPerMatrixMul * 1.0e-9f) / (msecPerMatrixMul / 1000.0f);
                    
                        printf("\n===========================================================\n");
                        printf("Input size: %d X %d X %d X %d\n", N_B, N_C, N_H, N_W);
                        printf("Kernel size: %d X %d X %d X %d\n", N_F, N_C, N_R, N_S);
                        printf("Output size: %d X %d X %d X %d\n", N_B, N_F, N_Y, N_X);
                        printf("flops: %0.5lf\n", (flopsPerMatrixMul * 1.0e-9f));
                        printf("Time is %0.5lf \n", (msecPerMatrixMul / 1000.0f));
                        printf("Gflops %0.5lf \n", gigaFlops);
                        printf("===========================================================\n");
                    
                        /*write back to Host Output -- batch size is 1*/
                        CHECK(cudaMemcpy(Output, dev_Output, sizeof(float) * N_B * N_F * N_X * N_Y, cudaMemcpyDeviceToHost));
                    
                        CHECK(cudaFree(dev_Input));
                        CHECK(cudaFree(dev_Kernel));
                        CHECK(cudaFree(dev_Output));
                    
                    }
            