
            #include <cassert>
            #include <stdlib.h>
            #include <cuda.h>
            #include "common.h"
            

            
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[6];
  __shared__ float pad_temp_shared[1160];
  __shared__ float kernel_shared[576];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 8; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[(((int)threadIdx.x))] = data[((((rc_outer_outer * 6728) + ((((int)blockIdx.x) % 9) * 87)) + ((int)threadIdx.x)))];
    pad_temp_shared[((((int)threadIdx.x) + 108))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 108) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + ((((int)threadIdx.x) + 108) % 145)))];
    pad_temp_shared[((((int)threadIdx.x) + 216))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 216) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + ((((int)threadIdx.x) + 71) % 145)))];
    pad_temp_shared[((((int)threadIdx.x) + 324))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 324) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + (((int)threadIdx.x) + 34)))];
    pad_temp_shared[((((int)threadIdx.x) + 432))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 432) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + ((((int)threadIdx.x) + 142) % 145)))];
    pad_temp_shared[((((int)threadIdx.x) + 540))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 540) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + ((((int)threadIdx.x) + 105) % 145)))];
    pad_temp_shared[((((int)threadIdx.x) + 648))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 648) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + ((((int)threadIdx.x) + 68) % 145)))];
    pad_temp_shared[((((int)threadIdx.x) + 756))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 756) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + (((int)threadIdx.x) + 31)))];
    pad_temp_shared[((((int)threadIdx.x) + 864))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 864) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + ((((int)threadIdx.x) + 139) % 145)))];
    pad_temp_shared[((((int)threadIdx.x) + 972))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 972) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + ((((int)threadIdx.x) + 102) % 145)))];
    if (((int)threadIdx.x) < 80) {
      pad_temp_shared[((((int)threadIdx.x) + 1080))] = data[(((((rc_outer_outer * 6728) + (((((int)threadIdx.x) + 1080) / 145) * 841)) + ((((int)blockIdx.x) % 9) * 87)) + (((int)threadIdx.x) + 65)))];
    }
    kernel_shared[(((int)threadIdx.x))] = kernel[((((((((int)blockIdx.x) / 9) * 4608) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 108))] = kernel[(((((((((int)blockIdx.x) / 9) * 4608) + (((((int)threadIdx.x) + 108) / 72) * 576)) + (rc_outer_outer * 72)) + ((((((int)threadIdx.x) / 9) + 4) & 7) * 9)) + (((int)threadIdx.x) % 9)))];
    kernel_shared[((((int)threadIdx.x) + 216))] = kernel[(((((((((int)blockIdx.x) / 9) * 4608) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)) + 1728))];
    kernel_shared[((((int)threadIdx.x) + 324))] = kernel[(((((((((int)blockIdx.x) / 9) * 4608) + (((((int)threadIdx.x) + 324) / 72) * 576)) + (rc_outer_outer * 72)) + ((((((int)threadIdx.x) / 9) + 4) & 7) * 9)) + (((int)threadIdx.x) % 9)))];
    kernel_shared[((((int)threadIdx.x) + 432))] = kernel[(((((((((int)blockIdx.x) / 9) * 4608) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)) + 3456))];
    if (((int)threadIdx.x) < 36) {
      kernel_shared[((((int)threadIdx.x) + 540))] = kernel[(((((((((int)blockIdx.x) / 9) * 4608) + (((((int)threadIdx.x) + 540) / 72) * 576)) + (rc_outer_outer * 72)) + (((((int)threadIdx.x) / 9) + 4) * 9)) + (((int)threadIdx.x) % 9)))];
    }
    __syncthreads();
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) % 27))] * kernel_shared[(((((int)threadIdx.x) / 27) * 144))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 29))] * kernel_shared[(((((int)threadIdx.x) / 27) * 144))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 58))] * kernel_shared[(((((int)threadIdx.x) / 27) * 144))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 29))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 3))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 58))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 3))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 87))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 3))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 58))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 6))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 87))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 6))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 116))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 6))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 145))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 9))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 174))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 9))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 203))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 9))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 174))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 12))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 203))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 12))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 232))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 12))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 203))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 15))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 232))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 15))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 261))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 15))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) % 27))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 72))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 29))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 72))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 58))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 72))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 29))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 75))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 58))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 75))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 87))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 75))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 58))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 78))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 87))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 78))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 116))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 78))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 145))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 81))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 174))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 81))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 203))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 81))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 174))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 84))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 203))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 84))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 232))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 84))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 203))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 87))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 232))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 87))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 261))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 87))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 1))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 30))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 1))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 59))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 1))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 30))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 4))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 59))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 4))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 88))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 4))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 59))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 7))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 88))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 7))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 117))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 7))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 146))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 10))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 175))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 10))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 204))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 10))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 175))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 13))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 204))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 13))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 233))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 13))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 204))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 16))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 233))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 16))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 262))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 16))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 73))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 30))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 73))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 59))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 73))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 30))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 76))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 59))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 76))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 88))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 76))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 59))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 79))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 88))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 79))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 117))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 79))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 146))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 82))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 175))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 82))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 204))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 82))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 175))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 85))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 204))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 85))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 233))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 85))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 204))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 88))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 233))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 88))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 262))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 88))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 2))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 2))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 31))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 2))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 60))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 2))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 31))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 5))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 60))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 5))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 89))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 5))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 60))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 8))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 89))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 8))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 118))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 8))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 147))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 11))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 176))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 11))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 205))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 11))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 176))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 14))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 205))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 14))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 234))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 14))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 205))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 17))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 234))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 17))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 263))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 17))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 2))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 74))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 31))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 74))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 60))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 74))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 31))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 77))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 60))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 77))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 89))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 77))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 60))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 80))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 89))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 80))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 118))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 80))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 147))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 83))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 176))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 83))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 205))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 83))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 176))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 86))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 205))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 86))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 234))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 86))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 205))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 89))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 234))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 89))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 263))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 89))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 290))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 18))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 319))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 18))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 348))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 18))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 319))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 21))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 348))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 21))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 377))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 21))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 348))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 24))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 377))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 24))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 406))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 24))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 435))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 27))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 464))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 27))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 493))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 27))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 464))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 30))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 493))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 30))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 522))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 30))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 493))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 33))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 522))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 33))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 551))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 33))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 290))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 90))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 319))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 90))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 348))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 90))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 319))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 93))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 348))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 93))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 377))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 93))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 348))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 96))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 377))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 96))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 406))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 96))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 435))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 99))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 464))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 99))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 493))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 99))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 464))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 102))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 493))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 102))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 522))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 102))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 493))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 105))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 522))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 105))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 551))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 105))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 291))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 19))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 320))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 19))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 349))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 19))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 320))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 22))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 349))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 22))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 378))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 22))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 349))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 25))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 378))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 25))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 407))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 25))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 436))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 28))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 465))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 28))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 494))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 28))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 465))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 31))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 494))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 31))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 523))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 31))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 494))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 34))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 523))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 34))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 552))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 34))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 291))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 91))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 320))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 91))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 349))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 91))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 320))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 94))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 349))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 94))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 378))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 94))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 349))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 97))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 378))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 97))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 407))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 97))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 436))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 100))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 465))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 100))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 494))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 100))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 465))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 103))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 494))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 103))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 523))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 103))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 494))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 106))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 523))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 106))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 552))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 106))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 292))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 20))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 321))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 20))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 350))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 20))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 321))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 23))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 350))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 23))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 379))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 23))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 350))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 26))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 379))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 26))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 408))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 26))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 437))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 29))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 466))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 29))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 495))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 29))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 466))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 32))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 495))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 32))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 524))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 32))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 495))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 35))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 524))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 35))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 553))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 35))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 292))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 92))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 321))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 92))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 350))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 92))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 321))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 95))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 350))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 95))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 379))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 95))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 350))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 98))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 379))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 98))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 408))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 98))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 437))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 101))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 466))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 101))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 495))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 101))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 466))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 104))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 495))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 104))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 524))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 104))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 495))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 107))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 524))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 107))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 553))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 107))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 580))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 36))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 609))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 36))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 638))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 36))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 609))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 39))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 638))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 39))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 667))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 39))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 638))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 42))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 667))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 42))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 696))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 42))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 725))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 45))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 754))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 45))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 783))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 45))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 754))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 48))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 783))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 48))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 812))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 48))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 783))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 51))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 812))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 51))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 841))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 51))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 580))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 108))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 609))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 108))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 638))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 108))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 609))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 111))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 638))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 111))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 667))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 111))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 638))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 114))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 667))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 114))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 696))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 114))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 725))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 117))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 754))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 117))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 783))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 117))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 754))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 120))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 783))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 120))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 812))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 120))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 783))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 123))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 812))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 123))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 841))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 123))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 581))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 37))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 610))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 37))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 639))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 37))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 610))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 40))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 639))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 40))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 668))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 40))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 639))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 43))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 668))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 43))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 697))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 43))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 726))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 46))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 755))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 46))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 784))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 46))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 755))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 49))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 784))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 49))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 813))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 49))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 784))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 52))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 813))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 52))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 842))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 52))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 581))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 109))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 610))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 109))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 639))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 109))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 610))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 112))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 639))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 112))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 668))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 112))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 639))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 115))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 668))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 115))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 697))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 115))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 726))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 118))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 755))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 118))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 784))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 118))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 755))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 121))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 784))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 121))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 813))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 121))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 784))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 124))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 813))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 124))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 842))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 124))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 582))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 38))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 611))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 38))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 640))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 38))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 611))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 41))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 640))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 41))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 669))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 41))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 640))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 44))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 669))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 44))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 698))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 44))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 727))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 47))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 756))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 47))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 785))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 47))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 756))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 50))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 785))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 50))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 814))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 50))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 785))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 53))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 814))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 53))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 843))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 53))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 582))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 110))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 611))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 110))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 640))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 110))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 611))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 113))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 640))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 113))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 669))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 113))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 640))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 116))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 669))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 116))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 698))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 116))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 727))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 119))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 756))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 119))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 785))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 119))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 756))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 122))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 785))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 122))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 814))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 122))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 785))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 125))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 814))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 125))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 843))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 125))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 870))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 54))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 899))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 54))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 928))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 54))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 899))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 57))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 928))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 57))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 957))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 57))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 928))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 60))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 957))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 60))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 986))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 60))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1015))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 63))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1044))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 63))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1073))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 63))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1044))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 66))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1073))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 66))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1102))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 66))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1073))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 69))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1102))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 69))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1131))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 69))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 870))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 126))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 899))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 126))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 928))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 126))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 899))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 129))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 928))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 129))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 957))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 129))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 928))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 132))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 957))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 132))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 986))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 132))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1015))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 135))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1044))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 135))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1073))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 135))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1044))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 138))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1073))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 138))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1102))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 138))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1073))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 141))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1102))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 141))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1131))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 141))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 871))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 55))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 900))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 55))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 929))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 55))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 900))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 58))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 929))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 58))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 958))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 58))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 929))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 61))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 958))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 61))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 987))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 61))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1016))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 64))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1045))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 64))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1074))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 64))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1045))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 67))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1074))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 67))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1103))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 67))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1074))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 70))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1103))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 70))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1132))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 70))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 871))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 127))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 900))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 127))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 929))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 127))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 900))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 130))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 929))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 130))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 958))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 130))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 929))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 133))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 958))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 133))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 987))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 133))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1016))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 136))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1045))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 136))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1074))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 136))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1045))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 139))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1074))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 139))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1103))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 139))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1074))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 142))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1103))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 142))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1132))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 142))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 872))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 56))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 901))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 56))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 930))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 56))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 901))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 59))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 930))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 59))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 959))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 59))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 930))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 62))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 959))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 62))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 988))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 62))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1017))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 65))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1046))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 65))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1075))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 65))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1046))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 68))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1075))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 68))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1104))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 68))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1075))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 71))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1104))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 71))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1133))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 71))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 872))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 128))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 901))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 128))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 930))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 128))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 901))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 131))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 930))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 131))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 959))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 131))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 930))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 134))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 959))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 134))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 988))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 134))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1017))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 137))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1046))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 137))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1075))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 137))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1046))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 140))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1075))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 140))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1104))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 140))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1075))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 143))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1104))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 143))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 27) + 1133))] * kernel_shared[((((((int)threadIdx.x) / 27) * 144) + 143))]));
  }
  for (int ff_inner = 0; ff_inner < 2; ++ff_inner) {
    for (int yy_inner = 0; yy_inner < 3; ++yy_inner) {
      compute[((((((((((int)blockIdx.x) / 9) * 5832) + ((((int)threadIdx.x) / 27) * 1458)) + (ff_inner * 729)) + ((((int)blockIdx.x) % 9) * 81)) + (yy_inner * 27)) + (((int)threadIdx.x) % 27)))] = compute_local[(((ff_inner * 3) + yy_inner))];
    }
  }
}



void conv_kernel_wrapper(int N_B, int N_C, int N_H, int N_W, int N_F, int N_R, int N_S, int PaddingH, int PaddingW,
                        int StrideH, int StrideW, int N_X, int N_Y, const float *Input, 
                        const float *Kernel, float *Output, int itr) {
                        cudaEvent_t start;
                        CHECK(cudaEventCreate(&start));
                        cudaEvent_t stop;
                        CHECK(cudaEventCreate(&stop));
                        float *dev_Input;
                        float *dev_Kernel;
                        float *dev_Output;
                    
                        CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                        CHECK(cudaMemcpy(dev_Kernel, Kernel, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                        CHECK(cudaMemcpy(dev_Input, Input, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Output, sizeof(float) * N_B * N_F * N_Y * N_X));
                        CHECK(cudaMemset(dev_Output, 0, sizeof(float) * N_B * N_F * N_Y * N_X));
                    
dim3 size_grid(144,1,1);

dim3 size_block(108,1,1);
 
                       printf("warmup....\n");
                        default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                    
                        double *time_arr = (double *)malloc(itr * sizeof(double));
                        for (int j = 1; j < itr; j++) {
                            CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                            CHECK(cudaMemcpy(dev_Kernel, Kernel+j*N_F * N_C * N_R * N_S, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                            CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                            CHECK(cudaMemcpy(dev_Input, Input+j*N_B * N_C * N_H * N_W, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                            /* Record the start event*/
                            CHECK(cudaEventRecord(start, NULL));
                            default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                            /* Record the end event */
                            CHECK(cudaEventRecord(stop, NULL));
                            /* Wait for the stop event to complete*/
                            CHECK(cudaEventSynchronize(stop));
                            float msec = 0.0f;
                            cudaEventElapsedTime(&msec, start, stop);
                            time_arr[j] = msec;
                        }
                    
                       
                    
                        //cudaError_t err = cudaGetLastError();
                        //if (err != cudaSuccess) printf("Error: %s\n", cudaGetErrorString(err));
                        double msecTotal = 0;
                        for (int j = 1; j < itr; j++) {   
                            printf("%0.5lf\n", time_arr[j]);
                            msecTotal += time_arr[j];
                        }
                    
                        double msecPerMatrixMul = (msecTotal) / itr;
                        double flopsPerMatrixMul = 2.0 * N_B * N_C * N_X * N_Y * N_F * N_R * N_S;
                    
                        double gigaFlops = (flopsPerMatrixMul * 1.0e-9f) / (msecPerMatrixMul / 1000.0f);
                    
                        printf("\n===========================================================\n");
                        printf("Input size: %d X %d X %d X %d\n", N_B, N_C, N_H, N_W);
                        printf("Kernel size: %d X %d X %d X %d\n", N_F, N_C, N_R, N_S);
                        printf("Output size: %d X %d X %d X %d\n", N_B, N_F, N_Y, N_X);
                        printf("flops: %0.5lf\n", (flopsPerMatrixMul * 1.0e-9f));
                        printf("Time is %0.5lf \n", (msecPerMatrixMul / 1000.0f));
                        printf("Gflops %0.5lf \n", gigaFlops);
                        printf("===========================================================\n");
                    
                        /*write back to Host Output -- batch size is 1*/
                        CHECK(cudaMemcpy(Output, dev_Output, sizeof(float) * N_B * N_F * N_X * N_Y, cudaMemcpyDeviceToHost));
                    
                        CHECK(cudaFree(dev_Input));
                        CHECK(cudaFree(dev_Kernel));
                        CHECK(cudaFree(dev_Output));
                    
                    }
            