
            #include <cassert>
            #include <stdlib.h>
            #include <cuda.h>
            #include "common.h"
            

            
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[32];
  __shared__ float pad_temp_shared[1088];
  __shared__ float kernel_shared[1024];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  compute_local[(8)] = 0.000000e+00f;
  compute_local[(9)] = 0.000000e+00f;
  compute_local[(10)] = 0.000000e+00f;
  compute_local[(11)] = 0.000000e+00f;
  compute_local[(12)] = 0.000000e+00f;
  compute_local[(13)] = 0.000000e+00f;
  compute_local[(14)] = 0.000000e+00f;
  compute_local[(15)] = 0.000000e+00f;
  compute_local[(16)] = 0.000000e+00f;
  compute_local[(17)] = 0.000000e+00f;
  compute_local[(18)] = 0.000000e+00f;
  compute_local[(19)] = 0.000000e+00f;
  compute_local[(20)] = 0.000000e+00f;
  compute_local[(21)] = 0.000000e+00f;
  compute_local[(22)] = 0.000000e+00f;
  compute_local[(23)] = 0.000000e+00f;
  compute_local[(24)] = 0.000000e+00f;
  compute_local[(25)] = 0.000000e+00f;
  compute_local[(26)] = 0.000000e+00f;
  compute_local[(27)] = 0.000000e+00f;
  compute_local[(28)] = 0.000000e+00f;
  compute_local[(29)] = 0.000000e+00f;
  compute_local[(30)] = 0.000000e+00f;
  compute_local[(31)] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 32; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[(((int)threadIdx.x))] = data[(((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)))];
    pad_temp_shared[((((int)threadIdx.x) + 136))] = data[((((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)) + 2312))];
    pad_temp_shared[((((int)threadIdx.x) + 272))] = data[((((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)) + 4624))];
    pad_temp_shared[((((int)threadIdx.x) + 408))] = data[((((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)) + 6936))];
    pad_temp_shared[((((int)threadIdx.x) + 544))] = data[((((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)) + 9248))];
    pad_temp_shared[((((int)threadIdx.x) + 680))] = data[((((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)) + 11560))];
    pad_temp_shared[((((int)threadIdx.x) + 816))] = data[((((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)) + 13872))];
    pad_temp_shared[((((int)threadIdx.x) + 952))] = data[((((((rc_outer_outer * 18496) + ((((int)threadIdx.x) / 68) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)) + 16184))];
    kernel_shared[(((int)threadIdx.x))] = kernel[((((((((int)blockIdx.x) / 17) * 32768) + ((((int)threadIdx.x) >> 4) * 512)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)))];
    kernel_shared[((((int)threadIdx.x) + 136))] = kernel[((((((((int)blockIdx.x) / 17) * 32768) + (((((int)threadIdx.x) + 136) >> 4) * 512)) + (rc_outer_outer * 16)) + ((((int)threadIdx.x) + 8) & 15)))];
    kernel_shared[((((int)threadIdx.x) + 272))] = kernel[(((((((((int)blockIdx.x) / 17) * 32768) + ((((int)threadIdx.x) >> 4) * 512)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 8704))];
    kernel_shared[((((int)threadIdx.x) + 408))] = kernel[((((((((int)blockIdx.x) / 17) * 32768) + (((((int)threadIdx.x) + 408) >> 4) * 512)) + (rc_outer_outer * 16)) + ((((int)threadIdx.x) + 8) & 15)))];
    kernel_shared[((((int)threadIdx.x) + 544))] = kernel[(((((((((int)blockIdx.x) / 17) * 32768) + ((((int)threadIdx.x) >> 4) * 512)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 17408))];
    kernel_shared[((((int)threadIdx.x) + 680))] = kernel[((((((((int)blockIdx.x) / 17) * 32768) + (((((int)threadIdx.x) + 680) >> 4) * 512)) + (rc_outer_outer * 16)) + ((((int)threadIdx.x) + 8) & 15)))];
    kernel_shared[((((int)threadIdx.x) + 816))] = kernel[(((((((((int)blockIdx.x) / 17) * 32768) + ((((int)threadIdx.x) >> 4) * 512)) + (rc_outer_outer * 16)) + (((int)threadIdx.x) & 15)) + 26112))];
    if (((int)threadIdx.x) < 72) {
      kernel_shared[((((int)threadIdx.x) + 952))] = kernel[((((((((int)blockIdx.x) / 17) * 32768) + (((((int)threadIdx.x) + 952) >> 4) * 512)) + (rc_outer_outer * 16)) + ((((int)threadIdx.x) + 8) & 15)))];
    }
    __syncthreads();
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[(((((int)threadIdx.x) / 34) * 256))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 1))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 2))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 3))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[(((((int)threadIdx.x) / 34) * 256))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 1))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 2))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 3))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 16))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 17))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 18))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 19))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 16))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 17))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 18))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 19))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 32))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 33))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 34))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 35))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 32))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 33))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 34))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 35))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 48))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 49))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 50))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 51))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 48))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 49))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 50))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 51))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 64))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 65))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 66))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 67))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 64))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 65))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 66))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 67))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 80))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 81))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 82))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 83))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 80))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 81))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 82))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 83))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 96))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 97))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 98))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 99))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 96))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 97))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 98))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 99))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 112))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 113))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 114))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 115))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 112))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 113))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 114))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 115))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 128))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 129))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 130))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 131))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 128))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 129))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 130))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 131))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 144))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 145))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 146))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 147))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 144))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 145))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 146))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 147))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 160))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 161))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 162))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 163))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 160))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 161))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 162))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 163))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 176))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 177))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 178))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 179))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 176))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 177))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 178))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 179))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 192))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 193))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 194))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 195))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 192))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 193))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 194))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 195))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 208))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 209))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 210))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 211))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 208))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 209))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 210))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 211))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 224))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 225))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 226))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 227))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 224))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 225))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 226))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 227))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[(((((int)threadIdx.x) % 34) * 2))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 240))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 68))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 241))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 136))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 242))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 204))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 243))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 240))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 69))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 241))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 137))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 242))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 205))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 243))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 4))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 5))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 6))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 7))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 4))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 5))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 6))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 7))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 20))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 21))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 22))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 23))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 20))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 21))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 22))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 23))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 36))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 37))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 38))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 39))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 36))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 37))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 38))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 39))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 52))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 53))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 54))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 55))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 52))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 53))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 54))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 55))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 68))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 69))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 70))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 71))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 68))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 69))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 70))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 71))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 84))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 85))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 86))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 87))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 84))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 85))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 86))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 87))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 100))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 101))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 102))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 103))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 100))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 101))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 102))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 103))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 116))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 117))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 118))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 119))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 116))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 117))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 118))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 119))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 132))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 133))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 134))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 135))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 132))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 133))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 134))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 135))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 148))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 149))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 150))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 151))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 148))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 149))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 150))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 151))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 164))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 165))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 166))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 167))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 164))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 165))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 166))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 167))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 180))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 181))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 182))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 183))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 180))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 181))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 182))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 183))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 196))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 197))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 198))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 199))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 196))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 197))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 198))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 199))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 212))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 213))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 214))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 215))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 212))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 213))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 214))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 215))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 228))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 229))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 230))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 231))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 228))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 229))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 230))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 231))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 272))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 244))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 340))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 245))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 408))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 246))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 476))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 247))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 273))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 244))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 341))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 245))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 409))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 246))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 477))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 247))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 8))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 9))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 10))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 11))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 8))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 9))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 10))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 11))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 24))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 25))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 26))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 27))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 24))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 25))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 26))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 27))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 40))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 41))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 42))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 43))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 40))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 41))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 42))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 43))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 56))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 57))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 58))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 59))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 56))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 57))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 58))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 59))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 72))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 73))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 74))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 75))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 72))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 73))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 74))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 75))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 88))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 89))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 90))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 91))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 88))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 89))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 90))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 91))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 104))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 105))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 106))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 107))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 104))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 105))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 106))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 107))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 120))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 121))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 122))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 123))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 120))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 121))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 122))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 123))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 136))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 137))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 138))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 139))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 136))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 137))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 138))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 139))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 152))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 153))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 154))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 155))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 152))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 153))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 154))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 155))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 168))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 169))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 170))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 171))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 168))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 169))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 170))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 171))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 184))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 185))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 186))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 187))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 184))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 185))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 186))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 187))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 200))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 201))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 202))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 203))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 200))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 201))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 202))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 203))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 216))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 217))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 218))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 219))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 216))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 217))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 218))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 219))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 232))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 233))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 234))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 235))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 232))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 233))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 234))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 235))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 544))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 248))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 612))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 249))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 680))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 250))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 748))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 251))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 545))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 248))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 613))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 249))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 681))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 250))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 749))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 251))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 12))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 13))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 14))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 15))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 12))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 13))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 14))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 15))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 28))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 29))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 30))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 31))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 28))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 29))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 30))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 31))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 44))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 45))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 46))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 47))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 44))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 45))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 46))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 47))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 60))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 61))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 62))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 63))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 60))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 61))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 62))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 63))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 76))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 77))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 78))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 79))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 76))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 77))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 78))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 79))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 92))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 93))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 94))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 95))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 92))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 93))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 94))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 95))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 108))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 109))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 110))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 111))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 108))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 109))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 110))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 111))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 124))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 125))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 126))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 127))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 124))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 125))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 126))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 127))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 140))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 141))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 142))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 143))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 140))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 141))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 142))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 143))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 156))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 157))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 158))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 159))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 156))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 157))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 158))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 159))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 172))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 173))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 174))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 175))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 172))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 173))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 174))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 175))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 188))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 189))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 190))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 191))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 188))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 189))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 190))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 191))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 204))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 205))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 206))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 207))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 204))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 205))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 206))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 207))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 220))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 221))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 222))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 223))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 220))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 221))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 222))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 223))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 236))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 237))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 238))]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 239))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 236))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 237))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 238))]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 239))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 816))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 252))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 884))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 253))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 952))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 254))]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 255))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 817))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 252))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 885))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 253))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 953))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 254))]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((((int)threadIdx.x) % 34) * 2) + 1021))] * kernel_shared[((((((int)threadIdx.x) / 34) * 256) + 255))]));
  }
  for (int ff_inner = 0; ff_inner < 16; ++ff_inner) {
    for (int xx_inner = 0; xx_inner < 2; ++xx_inner) {
      compute[((((((((((int)blockIdx.x) / 17) * 73984) + ((((int)threadIdx.x) / 34) * 18496)) + (ff_inner * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + ((((int)threadIdx.x) % 34) * 2)) + xx_inner))] = compute_local[(((ff_inner * 2) + xx_inner))];
    }
  }
}



void conv_kernel_wrapper(int N_B, int N_C, int N_H, int N_W, int N_F, int N_R, int N_S, int PaddingH, int PaddingW,
                        int StrideH, int StrideW, int N_X, int N_Y, const float *Input, 
                        const float *Kernel, float *Output, int itr) {
                        cudaEvent_t start;
                        CHECK(cudaEventCreate(&start));
                        cudaEvent_t stop;
                        CHECK(cudaEventCreate(&stop));
                        float *dev_Input;
                        float *dev_Kernel;
                        float *dev_Output;
                    
                        CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                        CHECK(cudaMemcpy(dev_Kernel, Kernel, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                        CHECK(cudaMemcpy(dev_Input, Input, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Output, sizeof(float) * N_B * N_F * N_Y * N_X));
                        CHECK(cudaMemset(dev_Output, 0, sizeof(float) * N_B * N_F * N_Y * N_X));
                    
dim3 size_grid(68,1,1);

dim3 size_block(136,1,1);
 
                       printf("warmup....\n");
                        default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                    
                        double *time_arr = (double *)malloc(itr * sizeof(double));
                        for (int j = 1; j < itr; j++) {
                            CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                            CHECK(cudaMemcpy(dev_Kernel, Kernel+j*N_F * N_C * N_R * N_S, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                            CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                            CHECK(cudaMemcpy(dev_Input, Input+j*N_B * N_C * N_H * N_W, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                            /* Record the start event*/
                            CHECK(cudaEventRecord(start, NULL));
                            default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                            /* Record the end event */
                            CHECK(cudaEventRecord(stop, NULL));
                            /* Wait for the stop event to complete*/
                            CHECK(cudaEventSynchronize(stop));
                            float msec = 0.0f;
                            cudaEventElapsedTime(&msec, start, stop);
                            time_arr[j] = msec;
                        }
                    
                       
                    
                        //cudaError_t err = cudaGetLastError();
                        //if (err != cudaSuccess) printf("Error: %s\n", cudaGetErrorString(err));
                        double msecTotal = 0;
                        for (int j = 1; j < itr; j++) {   
                            printf("%0.5lf\n", time_arr[j]);
                            msecTotal += time_arr[j];
                        }
                    
                        double msecPerMatrixMul = (msecTotal) / itr;
                        double flopsPerMatrixMul = 2.0 * N_B * N_C * N_X * N_Y * N_F * N_R * N_S;
                    
                        double gigaFlops = (flopsPerMatrixMul * 1.0e-9f) / (msecPerMatrixMul / 1000.0f);
                    
                        printf("\n===========================================================\n");
                        printf("Input size: %d X %d X %d X %d\n", N_B, N_C, N_H, N_W);
                        printf("Kernel size: %d X %d X %d X %d\n", N_F, N_C, N_R, N_S);
                        printf("Output size: %d X %d X %d X %d\n", N_B, N_F, N_Y, N_X);
                        printf("flops: %0.5lf\n", (flopsPerMatrixMul * 1.0e-9f));
                        printf("Time is %0.5lf \n", (msecPerMatrixMul / 1000.0f));
                        printf("Gflops %0.5lf \n", gigaFlops);
                        printf("===========================================================\n");
                    
                        /*write back to Host Output -- batch size is 1*/
                        CHECK(cudaMemcpy(Output, dev_Output, sizeof(float) * N_B * N_F * N_X * N_Y, cudaMemcpyDeviceToHost));
                    
                        CHECK(cudaFree(dev_Input));
                        CHECK(cudaFree(dev_Kernel));
                        CHECK(cudaFree(dev_Output));
                    
                    }
            