
            #include <cassert>
            #include <stdlib.h>
            #include <cuda.h>
            #include "common.h"
            

            
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[8];
  __shared__ float pad_temp_shared[2320];
  __shared__ float kernel_shared[4608];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 8; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[(((int)threadIdx.x))] = data[(((((rc_outer_outer * 14400) + ((((int)threadIdx.x) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + (((int)threadIdx.x) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 112))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 112) / 145) * 900)) + ((((((int)threadIdx.x) + 112) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 2) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 224))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 224) / 145) * 900)) + ((((((int)threadIdx.x) + 79) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 4) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 336))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 336) / 145) * 900)) + ((((((int)threadIdx.x) + 46) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 1) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 448))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 448) / 145) * 900)) + (((((int)threadIdx.x) + 13) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 3) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 560))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 560) / 145) * 900)) + ((((((int)threadIdx.x) + 125) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + (((int)threadIdx.x) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 672))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 672) / 145) * 900)) + ((((((int)threadIdx.x) + 92) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 2) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 784))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 784) / 145) * 900)) + ((((((int)threadIdx.x) + 59) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 4) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 896))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 896) / 145) * 900)) + (((((int)threadIdx.x) + 26) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 1) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1008))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1008) / 145) * 900)) + ((((((int)threadIdx.x) + 138) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 3) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1120))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1120) / 145) * 900)) + ((((((int)threadIdx.x) + 105) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + (((int)threadIdx.x) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1232))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1232) / 145) * 900)) + ((((((int)threadIdx.x) + 72) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 2) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1344))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1344) / 145) * 900)) + ((((((int)threadIdx.x) + 39) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 4) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1456))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1456) / 145) * 900)) + (((((int)threadIdx.x) + 6) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 1) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1568))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1568) / 145) * 900)) + ((((((int)threadIdx.x) + 118) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 3) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1680))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1680) / 145) * 900)) + ((((((int)threadIdx.x) + 85) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + (((int)threadIdx.x) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1792))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1792) / 145) * 900)) + ((((((int)threadIdx.x) + 52) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 2) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 1904))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 1904) / 145) * 900)) + (((((int)threadIdx.x) + 19) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 4) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 2016))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 2016) / 145) * 900)) + ((((((int)threadIdx.x) + 131) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 1) % 5)))];
    pad_temp_shared[((((int)threadIdx.x) + 2128))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 2128) / 145) * 900)) + ((((((int)threadIdx.x) + 98) % 145) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + ((((int)threadIdx.x) + 3) % 5)))];
    if (((int)threadIdx.x) < 80) {
      pad_temp_shared[((((int)threadIdx.x) + 2240))] = data[((((((rc_outer_outer * 14400) + (((((int)threadIdx.x) + 2240) / 145) * 900)) + (((((int)threadIdx.x) + 65) / 5) * 30)) + ((((int)blockIdx.x) % 7) * 4)) + (((int)threadIdx.x) % 5)))];
    }
    kernel_shared[((((int)threadIdx.x) * 3))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 336))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 112) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 337))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 112) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 338))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 112) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 672))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 224) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 673))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 224) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 674))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 224) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1008))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 8064))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1009))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 8065))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1010))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 8066))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1344))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 448) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1345))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 448) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1346))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 448) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1680))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 560) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1681))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 560) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 1682))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 560) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2016))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 16128))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2017))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 16129))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2018))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 16130))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2352))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 784) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2353))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 784) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2354))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 784) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2688))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 896) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2689))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 896) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 2690))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 896) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3024))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 24192))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3025))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 24193))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3026))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 24194))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3360))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1120) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3361))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1120) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3362))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1120) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3696))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1232) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3697))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1232) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 1))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 3698))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1232) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 32) % 48) * 3)) + 2))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 4032))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 32256))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 4033))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 32257))];
    kernel_shared[(((((int)threadIdx.x) * 3) + 4034))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + ((((int)threadIdx.x) / 48) * 1152)) + (rc_outer_outer * 144)) + ((((int)threadIdx.x) % 48) * 3)) + 32258))];
    if (((int)threadIdx.x) < 80) {
      kernel_shared[(((((int)threadIdx.x) * 3) + 4368))] = kernel[((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1456) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)))];
      kernel_shared[(((((int)threadIdx.x) * 3) + 4369))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1456) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 1))];
      kernel_shared[(((((int)threadIdx.x) * 3) + 4370))] = kernel[(((((((((int)blockIdx.x) / 7) * 36864) + (((((int)threadIdx.x) + 1456) / 48) * 1152)) + (rc_outer_outer * 144)) + (((((int)threadIdx.x) + 16) % 48) * 3)) + 2))];
    }
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 4; ++rc_outer_inner) {
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)))] * kernel_shared[((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1152))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2304))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3456))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1152))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2304))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3456))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 1))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 1))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1153))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 1))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2305))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 1))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3457))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1153))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2305))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3457))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1154))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2306))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3458))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1154))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2306))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3458))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 5))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 5))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1155))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 5))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2307))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 5))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3459))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 15))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 15))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1155))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 15))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2307))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 15))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3459))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 6))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 4))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 6))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1156))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 6))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2308))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 6))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3460))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 16))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 4))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 16))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1156))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 16))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2308))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 16))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3460))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 7))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 5))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 7))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1157))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 7))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2309))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 7))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3461))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 17))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 5))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 17))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1157))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 17))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2309))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 17))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3461))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 6))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1158))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2310))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 10))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3462))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 20))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 6))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 20))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1158))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 20))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2310))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 20))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3462))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 7))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1159))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2311))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 11))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3463))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 21))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 7))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 21))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1159))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 21))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2311))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 21))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3463))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 8))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1160))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2312))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 12))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3464))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 22))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 8))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 22))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1160))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 22))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2312))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 22))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3464))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 145))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 9))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 145))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1161))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 145))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2313))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 145))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3465))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 9))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1161))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2313))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3465))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 146))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 10))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 146))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1162))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 146))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2314))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 146))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3466))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 10))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1162))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2314))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3466))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 147))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 11))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 147))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1163))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 147))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2315))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 147))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3467))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 11))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1163))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2315))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3467))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 150))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 12))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 150))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1164))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 150))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2316))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 150))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3468))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 160))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 12))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 160))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1164))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 160))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2316))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 160))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3468))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 151))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 13))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 151))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1165))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 151))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2317))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 151))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3469))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 161))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 13))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 161))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1165))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 161))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2317))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 161))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3469))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 152))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 14))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 152))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1166))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 152))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2318))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 152))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3470))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 162))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 14))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 162))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1166))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 162))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2318))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 162))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3470))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 15))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1167))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2319))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 155))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3471))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 165))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 15))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 165))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1167))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 165))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2319))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 165))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3471))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 16))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1168))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2320))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 156))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3472))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 166))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 16))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 166))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1168))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 166))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2320))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 166))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3472))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 17))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1169))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2321))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 157))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3473))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 167))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 17))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 167))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1169))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 167))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2321))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 167))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3473))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 290))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 18))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 290))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1170))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 290))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2322))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 290))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3474))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 18))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1170))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2322))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3474))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 291))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 19))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 291))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1171))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 291))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2323))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 291))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3475))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 19))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1171))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2323))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3475))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 292))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 20))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 292))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1172))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 292))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2324))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 292))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3476))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 20))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1172))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2324))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3476))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 295))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 21))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 295))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1173))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 295))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2325))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 295))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3477))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 305))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 21))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 305))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1173))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 305))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2325))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 305))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3477))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 296))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 22))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 296))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1174))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 296))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2326))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 296))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3478))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 306))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 22))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 306))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1174))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 306))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2326))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 306))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3478))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 297))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 23))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 297))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1175))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 297))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2327))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 297))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3479))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 307))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 23))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 307))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1175))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 307))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2327))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 307))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3479))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 24))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1176))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2328))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 300))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3480))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 310))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 24))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 310))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1176))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 310))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2328))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 310))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3480))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 25))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1177))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2329))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 301))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3481))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 311))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 25))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 311))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1177))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 311))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2329))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 311))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3481))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 26))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1178))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2330))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 302))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3482))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 312))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 26))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 312))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1178))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 312))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2330))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 312))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3482))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 435))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 27))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 435))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1179))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 435))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2331))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 435))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3483))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 27))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1179))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2331))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3483))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 436))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 28))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 436))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1180))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 436))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2332))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 436))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3484))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 28))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1180))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2332))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3484))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 437))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 29))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 437))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1181))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 437))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2333))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 437))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3485))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 29))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1181))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2333))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3485))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 440))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 30))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 440))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1182))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 440))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2334))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 440))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3486))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 450))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 30))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 450))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1182))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 450))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2334))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 450))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3486))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 441))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 31))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 441))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1183))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 441))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2335))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 441))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3487))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 451))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 31))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 451))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1183))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 451))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2335))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 451))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3487))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 442))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 32))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 442))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1184))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 442))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2336))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 442))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3488))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 452))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 32))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 452))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1184))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 452))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2336))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 452))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3488))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 33))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1185))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2337))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 445))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3489))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 455))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 33))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 455))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1185))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 455))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2337))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 455))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3489))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 34))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1186))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2338))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 446))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3490))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 456))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 34))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 456))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1186))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 456))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2338))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 456))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3490))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 35))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1187))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2339))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 447))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3491))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 457))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 35))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 457))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 1187))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 457))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 2339))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 580) + (((((int)threadIdx.x) % 14) >> 1) * 20)) + ((((int)threadIdx.x) & 1) * 2)) + 457))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 144) + (rc_outer_inner * 36)) + 3491))]));
    }
  }
  for (int yy_inner = 0; yy_inner < 2; ++yy_inner) {
    compute[(((((((((int)blockIdx.x) / 7) * 6272) + ((((int)threadIdx.x) >> 1) * 28)) + (yy_inner * 14)) + ((((int)blockIdx.x) % 7) * 2)) + (((int)threadIdx.x) & 1)))] = compute_local[(yy_inner)];
    compute[((((((((((int)blockIdx.x) / 7) * 6272) + ((((int)threadIdx.x) >> 1) * 28)) + (yy_inner * 14)) + ((((int)blockIdx.x) % 7) * 2)) + (((int)threadIdx.x) & 1)) + 1568))] = compute_local[((yy_inner + 2))];
    compute[((((((((((int)blockIdx.x) / 7) * 6272) + ((((int)threadIdx.x) >> 1) * 28)) + (yy_inner * 14)) + ((((int)blockIdx.x) % 7) * 2)) + (((int)threadIdx.x) & 1)) + 3136))] = compute_local[((yy_inner + 4))];
    compute[((((((((((int)blockIdx.x) / 7) * 6272) + ((((int)threadIdx.x) >> 1) * 28)) + (yy_inner * 14)) + ((((int)blockIdx.x) % 7) * 2)) + (((int)threadIdx.x) & 1)) + 4704))] = compute_local[((yy_inner + 6))];
  }
}



void conv_kernel_wrapper(int N_B, int N_C, int N_H, int N_W, int N_F, int N_R, int N_S, int PaddingH, int PaddingW,
                        int StrideH, int StrideW, int N_X, int N_Y, const float *Input, 
                        const float *Kernel, float *Output, int itr) {
                        cudaEvent_t start;
                        CHECK(cudaEventCreate(&start));
                        cudaEvent_t stop;
                        CHECK(cudaEventCreate(&stop));
                        float *dev_Input;
                        float *dev_Kernel;
                        float *dev_Output;
                    
                        CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                        CHECK(cudaMemcpy(dev_Kernel, Kernel, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                        CHECK(cudaMemcpy(dev_Input, Input, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Output, sizeof(float) * N_B * N_F * N_Y * N_X));
                        CHECK(cudaMemset(dev_Output, 0, sizeof(float) * N_B * N_F * N_Y * N_X));
                    
dim3 size_grid(56,1,1);

dim3 size_block(112,1,1);
 
                       printf("warmup....\n");
                        default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                    
                        double *time_arr = (double *)malloc(itr * sizeof(double));
                        for (int j = 1; j < itr; j++) {
                            CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                            CHECK(cudaMemcpy(dev_Kernel, Kernel+j*N_F * N_C * N_R * N_S, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                            CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                            CHECK(cudaMemcpy(dev_Input, Input+j*N_B * N_C * N_H * N_W, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                            /* Record the start event*/
                            CHECK(cudaEventRecord(start, NULL));
                            default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                            /* Record the end event */
                            CHECK(cudaEventRecord(stop, NULL));
                            /* Wait for the stop event to complete*/
                            CHECK(cudaEventSynchronize(stop));
                            float msec = 0.0f;
                            cudaEventElapsedTime(&msec, start, stop);
                            time_arr[j] = msec;
                        }
                    
                       
                    
                        //cudaError_t err = cudaGetLastError();
                        //if (err != cudaSuccess) printf("Error: %s\n", cudaGetErrorString(err));
                        double msecTotal = 0;
                        for (int j = 1; j < itr; j++) {   
                            printf("%0.5lf\n", time_arr[j]);
                            msecTotal += time_arr[j];
                        }
                    
                        double msecPerMatrixMul = (msecTotal) / itr;
                        double flopsPerMatrixMul = 2.0 * N_B * N_C * N_X * N_Y * N_F * N_R * N_S;
                    
                        double gigaFlops = (flopsPerMatrixMul * 1.0e-9f) / (msecPerMatrixMul / 1000.0f);
                    
                        printf("\n===========================================================\n");
                        printf("Input size: %d X %d X %d X %d\n", N_B, N_C, N_H, N_W);
                        printf("Kernel size: %d X %d X %d X %d\n", N_F, N_C, N_R, N_S);
                        printf("Output size: %d X %d X %d X %d\n", N_B, N_F, N_Y, N_X);
                        printf("flops: %0.5lf\n", (flopsPerMatrixMul * 1.0e-9f));
                        printf("Time is %0.5lf \n", (msecPerMatrixMul / 1000.0f));
                        printf("Gflops %0.5lf \n", gigaFlops);
                        printf("===========================================================\n");
                    
                        /*write back to Host Output -- batch size is 1*/
                        CHECK(cudaMemcpy(Output, dev_Output, sizeof(float) * N_B * N_F * N_X * N_Y, cudaMemcpyDeviceToHost));
                    
                        CHECK(cudaFree(dev_Input));
                        CHECK(cudaFree(dev_Kernel));
                        CHECK(cudaFree(dev_Output));
                    
                    }
            