
            #include <cassert>
            #include <stdlib.h>
            #include <cuda.h>
            #include "common.h"
            

            
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[8];
  __shared__ float pad_temp_shared[2280];
  __shared__ float kernel_shared[1152];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 8; ++rc_outer_outer) {
    __syncthreads();
    pad_temp_shared[((((int)threadIdx.x) * 2))] = data[(((((rc_outer_outer * 26912) + ((((int)blockIdx.x) % 14) * 232)) + (((((int)threadIdx.x) * 2) / 57) * 58)) + ((((int)threadIdx.x) * 2) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1))] = data[(((((rc_outer_outer * 26912) + ((((int)blockIdx.x) % 14) * 232)) + ((((((int)threadIdx.x) * 2) + 1) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 1) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 224))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 224) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 224) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 53) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 225))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 225) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 225) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 54) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 448))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 448) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 163) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 49) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 449))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 449) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 164) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 50) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 672))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 672) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 102) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 45) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 673))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 673) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 103) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 46) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 896))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 896) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + ((((((int)threadIdx.x) * 2) + 41) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 41) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 897))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 897) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + ((((((int)threadIdx.x) * 2) + 42) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 42) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1120))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1120) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 265) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 37) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1121))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1121) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 266) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 38) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1344))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1344) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 204) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 33) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1345))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1345) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 205) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 34) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1568))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1568) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 143) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 29) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1569))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1569) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 144) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 30) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1792))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1792) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 82) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 25) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 1793))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 1793) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + (((((((int)threadIdx.x) * 2) + 83) % 285) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 26) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 2016))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 2016) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + ((((((int)threadIdx.x) * 2) + 21) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 21) % 57)))];
    pad_temp_shared[(((((int)threadIdx.x) * 2) + 2017))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 2017) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + ((((((int)threadIdx.x) * 2) + 22) / 57) * 58)) + (((((int)threadIdx.x) * 2) + 22) % 57)))];
    if (((int)threadIdx.x) < 20) {
      pad_temp_shared[(((((int)threadIdx.x) * 2) + 2240))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 2240) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + ((((((int)threadIdx.x) * 2) + 245) / 57) * 58)) + ((((int)threadIdx.x) * 2) + 17)))];
    }
    if (((int)threadIdx.x) < 20) {
      pad_temp_shared[(((((int)threadIdx.x) * 2) + 2241))] = data[((((((rc_outer_outer * 26912) + ((((((int)threadIdx.x) * 2) + 2241) / 285) * 3364)) + ((((int)blockIdx.x) % 14) * 232)) + ((((((int)threadIdx.x) * 2) + 246) / 57) * 58)) + ((((int)threadIdx.x) * 2) + 18)))];
    }
    kernel_shared[(((int)threadIdx.x))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 112))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 112) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 40) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 224))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 224) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 8) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 336))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 336) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 48) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 448))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 448) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 16) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 560))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 560) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 56) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 672))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 672) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 24) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 784))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 784) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 64) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 896))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 896) / 72) * 576)) + (rc_outer_outer * 72)) + ((((int)threadIdx.x) + 32) % 72)))];
    kernel_shared[((((int)threadIdx.x) + 1008))] = kernel[(((((((((int)blockIdx.x) / 14) * 9216) + ((((int)threadIdx.x) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) % 72)) + 8064))];
    if (((int)threadIdx.x) < 32) {
      kernel_shared[((((int)threadIdx.x) + 1120))] = kernel[((((((((int)blockIdx.x) / 14) * 9216) + (((((int)threadIdx.x) + 1120) / 72) * 576)) + (rc_outer_outer * 72)) + (((int)threadIdx.x) + 40)))];
    }
    __syncthreads();
    for (int rc_outer_inner = 0; rc_outer_inner < 2; ++rc_outer_inner) {
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)))] * kernel_shared[((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 28))] * kernel_shared[((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 576))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 28))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 576))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 2))] * kernel_shared[((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 30))] * kernel_shared[((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 576))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 30))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 576))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 1))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 1))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 29))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 1))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 1))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 577))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 29))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 577))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 3))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 1))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 31))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 1))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 3))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 577))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 31))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 577))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 2))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 30))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 2))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 2))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 578))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 30))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 578))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 4))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 2))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 32))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 2))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 4))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 578))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 32))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 578))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 57))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 3))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 85))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 3))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 57))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 579))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 85))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 579))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 59))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 3))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 87))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 3))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 59))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 579))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 87))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 579))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 58))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 4))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 86))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 4))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 58))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 580))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 86))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 580))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 60))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 4))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 88))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 4))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 60))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 580))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 88))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 580))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 59))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 5))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 87))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 5))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 59))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 581))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 87))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 581))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 61))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 5))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 89))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 5))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 61))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 581))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 89))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 581))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 114))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 6))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 142))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 6))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 114))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 582))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 142))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 582))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 116))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 6))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 144))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 6))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 116))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 582))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 144))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 582))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 115))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 7))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 143))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 7))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 115))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 583))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 143))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 583))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 117))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 7))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 145))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 7))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 117))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 583))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 145))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 583))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 116))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 8))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 144))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 8))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 116))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 584))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 144))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 584))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 118))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 8))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 146))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 8))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 118))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 584))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 146))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 584))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 285))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 9))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 313))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 9))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 285))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 585))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 313))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 585))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 287))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 9))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 315))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 9))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 287))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 585))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 315))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 585))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 286))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 10))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 314))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 10))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 286))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 586))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 314))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 586))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 288))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 10))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 316))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 10))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 288))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 586))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 316))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 586))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 287))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 11))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 315))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 11))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 287))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 587))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 315))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 587))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 289))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 11))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 317))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 11))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 289))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 587))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 317))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 587))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 342))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 12))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 370))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 12))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 342))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 588))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 370))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 588))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 344))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 12))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 372))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 12))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 344))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 588))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 372))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 588))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 343))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 13))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 371))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 13))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 343))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 589))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 371))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 589))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 345))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 13))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 373))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 13))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 345))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 589))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 373))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 589))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 344))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 14))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 372))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 14))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 344))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 590))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 372))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 590))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 346))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 14))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 374))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 14))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 346))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 590))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 374))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 590))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 399))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 15))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 427))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 15))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 399))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 591))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 427))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 591))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 401))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 15))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 429))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 15))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 401))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 591))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 429))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 591))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 400))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 16))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 428))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 16))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 400))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 592))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 428))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 592))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 402))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 16))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 430))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 16))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 402))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 592))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 430))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 592))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 401))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 17))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 429))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 17))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 401))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 593))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 429))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 593))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 403))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 17))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 431))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 17))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 403))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 593))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 431))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 593))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 570))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 18))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 598))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 18))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 570))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 594))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 598))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 594))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 572))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 18))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 600))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 18))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 572))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 594))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 600))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 594))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 571))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 19))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 599))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 19))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 571))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 595))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 599))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 595))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 573))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 19))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 601))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 19))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 573))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 595))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 601))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 595))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 572))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 20))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 600))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 20))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 572))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 596))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 600))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 596))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 574))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 20))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 602))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 20))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 574))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 596))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 602))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 596))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 627))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 21))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 655))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 21))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 627))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 597))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 655))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 597))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 629))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 21))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 657))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 21))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 629))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 597))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 657))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 597))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 628))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 22))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 656))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 22))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 628))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 598))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 656))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 598))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 630))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 22))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 658))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 22))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 630))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 598))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 658))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 598))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 629))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 23))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 657))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 23))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 629))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 599))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 657))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 599))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 631))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 23))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 659))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 23))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 631))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 599))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 659))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 599))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 684))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 24))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 712))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 24))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 684))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 600))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 712))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 600))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 686))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 24))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 714))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 24))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 686))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 600))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 714))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 600))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 685))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 25))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 713))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 25))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 685))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 601))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 713))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 601))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 687))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 25))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 715))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 25))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 687))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 601))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 715))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 601))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 686))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 26))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 714))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 26))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 686))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 602))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 714))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 602))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 688))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 26))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 716))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 26))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 688))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 602))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 716))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 602))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 855))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 27))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 883))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 27))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 855))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 603))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 883))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 603))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 857))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 27))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 885))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 27))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 857))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 603))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 885))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 603))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 856))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 28))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 884))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 28))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 856))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 604))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 884))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 604))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 858))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 28))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 886))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 28))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 858))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 604))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 886))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 604))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 857))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 29))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 885))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 29))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 857))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 605))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 885))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 605))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 859))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 29))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 887))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 29))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 859))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 605))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 887))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 605))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 912))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 30))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 940))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 30))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 912))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 606))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 940))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 606))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 914))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 30))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 942))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 30))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 914))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 606))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 942))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 606))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 913))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 31))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 941))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 31))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 913))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 607))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 941))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 607))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 915))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 31))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 943))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 31))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 915))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 607))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 943))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 607))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 914))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 32))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 942))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 32))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 914))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 608))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 942))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 608))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 916))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 32))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 944))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 32))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 916))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 608))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 944))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 608))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 969))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 33))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 997))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 33))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 969))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 609))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 997))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 609))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 971))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 33))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 999))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 33))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 971))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 609))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 999))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 609))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 970))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 34))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 998))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 34))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 970))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 610))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 998))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 610))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 972))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 34))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 1000))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 34))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 972))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 610))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 1000))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 610))]));
      compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 971))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 35))]));
      compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 999))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 35))]));
      compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 971))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 611))]));
      compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 999))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 611))]));
      compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 973))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 35))]));
      compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 1001))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 35))]));
      compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 973))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 611))]));
      compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((rc_outer_inner * 1140) + (((((int)threadIdx.x) % 14) / 7) * 114)) + ((((int)threadIdx.x) % 7) * 4)) + 1001))] * kernel_shared[(((((((int)threadIdx.x) / 14) * 72) + (rc_outer_inner * 36)) + 611))]));
    }
  }
  for (int xx_inner = 0; xx_inner < 2; ++xx_inner) {
    compute[((((((((((int)blockIdx.x) / 14) * 12544) + ((((int)threadIdx.x) / 14) * 784)) + ((((int)blockIdx.x) % 14) * 56)) + (((((int)threadIdx.x) % 14) / 7) * 28)) + ((((int)threadIdx.x) % 7) * 2)) + xx_inner))] = compute_local[(xx_inner)];
    compute[(((((((((((int)blockIdx.x) / 14) * 12544) + ((((int)threadIdx.x) / 14) * 784)) + ((((int)blockIdx.x) % 14) * 56)) + (((((int)threadIdx.x) % 14) / 7) * 28)) + ((((int)threadIdx.x) % 7) * 2)) + xx_inner) + 14))] = compute_local[((xx_inner + 2))];
    compute[(((((((((((int)blockIdx.x) / 14) * 12544) + ((((int)threadIdx.x) / 14) * 784)) + ((((int)blockIdx.x) % 14) * 56)) + (((((int)threadIdx.x) % 14) / 7) * 28)) + ((((int)threadIdx.x) % 7) * 2)) + xx_inner) + 6272))] = compute_local[((xx_inner + 4))];
    compute[(((((((((((int)blockIdx.x) / 14) * 12544) + ((((int)threadIdx.x) / 14) * 784)) + ((((int)blockIdx.x) % 14) * 56)) + (((((int)threadIdx.x) % 14) / 7) * 28)) + ((((int)threadIdx.x) % 7) * 2)) + xx_inner) + 6286))] = compute_local[((xx_inner + 6))];
  }
}



void conv_kernel_wrapper(int N_B, int N_C, int N_H, int N_W, int N_F, int N_R, int N_S, int PaddingH, int PaddingW,
                        int StrideH, int StrideW, int N_X, int N_Y, const float *Input, 
                        const float *Kernel, float *Output, int itr) {
                        cudaEvent_t start;
                        CHECK(cudaEventCreate(&start));
                        cudaEvent_t stop;
                        CHECK(cudaEventCreate(&stop));
                        float *dev_Input;
                        float *dev_Kernel;
                        float *dev_Output;
                    
                        CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                        CHECK(cudaMemcpy(dev_Kernel, Kernel, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                        CHECK(cudaMemcpy(dev_Input, Input, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Output, sizeof(float) * N_B * N_F * N_Y * N_X));
                        CHECK(cudaMemset(dev_Output, 0, sizeof(float) * N_B * N_F * N_Y * N_X));
                    
dim3 size_grid(112,1,1);

dim3 size_block(112,1,1);
 
                       printf("warmup....\n");
                        default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                    
                        double *time_arr = (double *)malloc(itr * sizeof(double));
                        for (int j = 1; j < itr; j++) {
                            CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                            CHECK(cudaMemcpy(dev_Kernel, Kernel+j*N_F * N_C * N_R * N_S, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                            CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                            CHECK(cudaMemcpy(dev_Input, Input+j*N_B * N_C * N_H * N_W, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                            /* Record the start event*/
                            CHECK(cudaEventRecord(start, NULL));
                            default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                            /* Record the end event */
                            CHECK(cudaEventRecord(stop, NULL));
                            /* Wait for the stop event to complete*/
                            CHECK(cudaEventSynchronize(stop));
                            float msec = 0.0f;
                            cudaEventElapsedTime(&msec, start, stop);
                            time_arr[j] = msec;
                        }
                    
                       
                    
                        //cudaError_t err = cudaGetLastError();
                        //if (err != cudaSuccess) printf("Error: %s\n", cudaGetErrorString(err));
                        double msecTotal = 0;
                        for (int j = 1; j < itr; j++) {   
                            printf("%0.5lf\n", time_arr[j]);
                            msecTotal += time_arr[j];
                        }
                    
                        double msecPerMatrixMul = (msecTotal) / itr;
                        double flopsPerMatrixMul = 2.0 * N_B * N_C * N_X * N_Y * N_F * N_R * N_S;
                    
                        double gigaFlops = (flopsPerMatrixMul * 1.0e-9f) / (msecPerMatrixMul / 1000.0f);
                    
                        printf("\n===========================================================\n");
                        printf("Input size: %d X %d X %d X %d\n", N_B, N_C, N_H, N_W);
                        printf("Kernel size: %d X %d X %d X %d\n", N_F, N_C, N_R, N_S);
                        printf("Output size: %d X %d X %d X %d\n", N_B, N_F, N_Y, N_X);
                        printf("flops: %0.5lf\n", (flopsPerMatrixMul * 1.0e-9f));
                        printf("Time is %0.5lf \n", (msecPerMatrixMul / 1000.0f));
                        printf("Gflops %0.5lf \n", gigaFlops);
                        printf("===========================================================\n");
                    
                        /*write back to Host Output -- batch size is 1*/
                        CHECK(cudaMemcpy(Output, dev_Output, sizeof(float) * N_B * N_F * N_X * N_Y, cudaMemcpyDeviceToHost));
                    
                        CHECK(cudaFree(dev_Input));
                        CHECK(cudaFree(dev_Kernel));
                        CHECK(cudaFree(dev_Output));
                    
                    }
            