
            #include <cassert>
            #include <stdlib.h>
            #include <cuda.h>
            #include "common.h"
            

            
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[16];
  __shared__ float pad_temp_shared[2176];
  __shared__ float kernel_shared[1024];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  compute_local[(8)] = 0.000000e+00f;
  compute_local[(9)] = 0.000000e+00f;
  compute_local[(10)] = 0.000000e+00f;
  compute_local[(11)] = 0.000000e+00f;
  compute_local[(12)] = 0.000000e+00f;
  compute_local[(13)] = 0.000000e+00f;
  compute_local[(14)] = 0.000000e+00f;
  compute_local[(15)] = 0.000000e+00f;
  for (int rc_outer_outer = 0; rc_outer_outer < 16; ++rc_outer_outer) {
    __syncthreads();
      ((float4*)(pad_temp_shared + ((((int)threadIdx.x) * 4))))[0] = ((float4*)(data + (((((rc_outer_outer * 36992) + ((((int)threadIdx.x) / 17) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + ((((int)threadIdx.x) % 17) * 4)))))[0];
      ((float4*)(pad_temp_shared + (((((int)threadIdx.x) * 4) + 544))))[0] = ((float4*)(data + ((((((rc_outer_outer * 36992) + ((((int)threadIdx.x) / 17) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + ((((int)threadIdx.x) % 17) * 4)) + 9248))))[0];
      ((float4*)(pad_temp_shared + (((((int)threadIdx.x) * 4) + 1088))))[0] = ((float4*)(data + ((((((rc_outer_outer * 36992) + ((((int)threadIdx.x) / 17) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + ((((int)threadIdx.x) % 17) * 4)) + 18496))))[0];
      ((float4*)(pad_temp_shared + (((((int)threadIdx.x) * 4) + 1632))))[0] = ((float4*)(data + ((((((rc_outer_outer * 36992) + ((((int)threadIdx.x) / 17) * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + ((((int)threadIdx.x) % 17) * 4)) + 27744))))[0];
    kernel_shared[(((int)threadIdx.x))] = kernel[((((((((int)blockIdx.x) / 17) * 16384) + ((((int)threadIdx.x) >> 5) * 512)) + (rc_outer_outer * 32)) + (((int)threadIdx.x) & 31)))];
    kernel_shared[((((int)threadIdx.x) + 136))] = kernel[((((((((int)blockIdx.x) / 17) * 16384) + (((((int)threadIdx.x) + 136) >> 5) * 512)) + (rc_outer_outer * 32)) + ((((int)threadIdx.x) + 8) & 31)))];
    kernel_shared[((((int)threadIdx.x) + 272))] = kernel[((((((((int)blockIdx.x) / 17) * 16384) + (((((int)threadIdx.x) + 272) >> 5) * 512)) + (rc_outer_outer * 32)) + ((((int)threadIdx.x) + 16) & 31)))];
    kernel_shared[((((int)threadIdx.x) + 408))] = kernel[((((((((int)blockIdx.x) / 17) * 16384) + (((((int)threadIdx.x) + 408) >> 5) * 512)) + (rc_outer_outer * 32)) + ((((int)threadIdx.x) + 24) & 31)))];
    kernel_shared[((((int)threadIdx.x) + 544))] = kernel[(((((((((int)blockIdx.x) / 17) * 16384) + ((((int)threadIdx.x) >> 5) * 512)) + (rc_outer_outer * 32)) + (((int)threadIdx.x) & 31)) + 8704))];
    kernel_shared[((((int)threadIdx.x) + 680))] = kernel[((((((((int)blockIdx.x) / 17) * 16384) + (((((int)threadIdx.x) + 680) >> 5) * 512)) + (rc_outer_outer * 32)) + ((((int)threadIdx.x) + 8) & 31)))];
    kernel_shared[((((int)threadIdx.x) + 816))] = kernel[((((((((int)blockIdx.x) / 17) * 16384) + (((((int)threadIdx.x) + 816) >> 5) * 512)) + (rc_outer_outer * 32)) + ((((int)threadIdx.x) + 16) & 31)))];
    if (((int)threadIdx.x) < 72) {
      kernel_shared[((((int)threadIdx.x) + 952))] = kernel[((((((((int)blockIdx.x) / 17) * 16384) + (((((int)threadIdx.x) + 952) >> 5) * 512)) + (rc_outer_outer * 32)) + ((((int)threadIdx.x) + 24) & 31)))];
    }
    __syncthreads();
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[(((((int)threadIdx.x) / 68) * 512))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 1))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 2))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 3))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 4))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 5))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 6))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 7))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 8))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 9))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 10))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 11))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 12))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 13))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 14))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 15))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 32))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 33))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 34))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 35))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 36))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 37))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 38))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 39))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 40))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 41))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 42))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 43))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 44))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 45))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 46))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 47))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 64))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 65))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 66))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 67))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 68))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 69))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 70))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 71))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 72))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 73))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 74))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 75))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 76))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 77))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 78))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 79))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 96))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 97))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 98))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 99))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 100))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 101))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 102))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 103))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 104))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 105))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 106))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 107))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 108))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 109))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 110))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 111))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 128))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 129))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 130))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 131))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 132))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 133))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 134))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 135))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 136))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 137))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 138))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 139))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 140))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 141))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 142))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 143))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 160))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 161))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 162))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 163))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 164))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 165))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 166))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 167))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 168))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 169))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 170))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 171))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 172))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 173))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 174))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 175))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 192))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 193))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 194))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 195))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 196))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 197))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 198))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 199))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 200))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 201))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 202))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 203))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 204))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 205))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 206))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 207))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 224))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 225))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 226))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 227))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 228))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 229))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 230))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 231))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 232))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 233))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 234))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 235))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 236))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 237))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 238))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 239))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 256))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 257))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 258))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 259))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 260))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 261))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 262))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 263))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 264))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 265))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 266))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 267))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 268))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 269))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 270))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 271))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 288))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 289))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 290))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 291))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 292))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 293))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 294))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 295))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 296))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 297))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 298))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 299))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 300))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 301))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 302))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 303))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 320))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 321))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 322))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 323))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 324))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 325))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 326))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 327))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 328))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 329))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 330))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 331))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 332))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 333))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 334))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 335))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 352))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 353))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 354))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 355))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 356))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 357))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 358))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 359))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 360))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 361))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 362))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 363))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 364))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 365))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 366))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 367))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 384))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 385))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 386))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 387))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 388))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 389))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 390))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 391))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 392))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 393))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 394))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 395))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 396))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 397))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 398))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 399))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 416))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 417))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 418))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 419))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 420))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 421))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 422))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 423))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 424))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 425))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 426))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 427))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 428))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 429))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 430))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 431))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 448))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 449))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 450))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 451))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 452))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 453))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 454))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 455))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 456))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 457))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 458))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 459))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 460))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 461))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 462))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 463))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) % 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 480))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 68))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 481))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 136))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 482))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 204))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 483))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 272))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 484))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 340))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 485))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 408))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 486))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 476))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 487))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 544))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 488))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 612))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 489))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 680))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 490))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 748))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 491))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 816))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 492))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 884))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 493))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 952))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 494))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1020))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 495))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 16))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 17))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 18))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 19))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 20))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 21))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 22))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 23))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 24))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 25))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 26))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 27))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 28))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 29))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 30))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 31))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 48))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 49))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 50))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 51))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 52))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 53))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 54))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 55))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 56))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 57))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 58))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 59))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 60))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 61))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 62))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 63))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 80))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 81))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 82))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 83))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 84))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 85))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 86))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 87))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 88))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 89))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 90))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 91))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 92))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 93))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 94))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 95))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 112))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 113))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 114))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 115))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 116))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 117))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 118))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 119))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 120))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 121))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 122))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 123))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 124))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 125))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 126))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 127))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 144))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 145))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 146))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 147))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 148))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 149))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 150))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 151))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 152))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 153))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 154))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 155))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 156))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 157))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 158))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 159))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 176))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 177))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 178))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 179))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 180))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 181))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 182))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 183))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 184))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 185))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 186))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 187))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 188))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 189))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 190))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 191))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 208))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 209))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 210))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 211))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 212))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 213))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 214))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 215))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 216))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 217))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 218))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 219))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 220))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 221))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 222))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 223))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 240))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 241))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 242))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 243))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 244))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 245))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 246))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 247))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 248))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 249))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 250))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 251))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 252))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 253))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 254))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 255))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 272))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 273))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 274))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 275))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 276))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 277))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 278))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 279))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 280))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 281))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 282))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 283))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 284))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 285))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 286))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 287))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 304))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 305))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 306))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 307))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 308))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 309))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 310))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 311))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 312))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 313))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 314))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 315))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 316))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 317))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 318))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 319))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 336))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 337))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 338))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 339))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 340))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 341))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 342))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 343))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 344))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 345))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 346))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 347))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 348))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 349))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 350))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 351))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 368))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 369))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 370))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 371))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 372))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 373))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 374))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 375))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 376))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 377))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 378))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 379))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 380))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 381))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 382))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 383))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 400))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 401))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 402))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 403))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 404))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 405))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 406))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 407))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 408))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 409))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 410))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 411))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 412))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 413))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 414))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 415))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 432))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 433))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 434))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 435))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 436))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 437))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 438))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 439))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 440))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 441))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 442))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 443))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 444))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 445))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 446))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 447))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 464))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 465))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 466))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 467))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 468))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 469))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 470))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 471))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 472))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 473))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 474))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 475))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 476))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 477))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 478))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 479))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1088))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 496))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1156))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 497))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1224))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 498))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1292))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 499))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1360))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 500))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1428))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 501))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1496))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 502))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1564))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 503))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1632))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 504))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1700))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 505))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1768))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 506))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1836))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 507))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1904))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 508))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 1972))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 509))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2040))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 510))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((((int)threadIdx.x) % 68) + 2108))] * kernel_shared[((((((int)threadIdx.x) / 68) * 512) + 511))]));
  }
  for (int ff_inner = 0; ff_inner < 16; ++ff_inner) {
    compute[(((((((((int)blockIdx.x) / 17) * 36992) + ((((int)threadIdx.x) / 68) * 18496)) + (ff_inner * 1156)) + ((((int)blockIdx.x) % 17) * 68)) + (((int)threadIdx.x) % 68)))] = compute_local[(ff_inner)];
  }
}



void conv_kernel_wrapper(int N_B, int N_C, int N_H, int N_W, int N_F, int N_R, int N_S, int PaddingH, int PaddingW,
                        int StrideH, int StrideW, int N_X, int N_Y, const float *Input, 
                        const float *Kernel, float *Output, int itr) {
                        cudaEvent_t start;
                        CHECK(cudaEventCreate(&start));
                        cudaEvent_t stop;
                        CHECK(cudaEventCreate(&stop));
                        float *dev_Input;
                        float *dev_Kernel;
                        float *dev_Output;
                    
                        CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                        CHECK(cudaMemcpy(dev_Kernel, Kernel, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                        CHECK(cudaMemcpy(dev_Input, Input, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                        CHECK(cudaMalloc(&dev_Output, sizeof(float) * N_B * N_F * N_Y * N_X));
                        CHECK(cudaMemset(dev_Output, 0, sizeof(float) * N_B * N_F * N_Y * N_X));
                    
dim3 size_grid(136,1,1);

dim3 size_block(136,1,1);
 
                       printf("warmup....\n");
                        default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                    
                        double *time_arr = (double *)malloc(itr * sizeof(double));
                        for (int j = 1; j < itr; j++) {
                            CHECK(cudaMalloc(&dev_Kernel, sizeof(float) * N_F * N_C * N_R * N_S));
                            CHECK(cudaMemcpy(dev_Kernel, Kernel+j*N_F * N_C * N_R * N_S, sizeof(float) * N_F * N_C * N_R * N_S, cudaMemcpyHostToDevice));
                    
                            CHECK(cudaMalloc(&dev_Input, sizeof(float) * N_B * N_C * N_H * N_W));
                            CHECK(cudaMemcpy(dev_Input, Input+j*N_B * N_C * N_H * N_W, sizeof(float) * N_B * N_C * N_H * N_W, cudaMemcpyHostToDevice));
                    
                            /* Record the start event*/
                            CHECK(cudaEventRecord(start, NULL));
                            default_function_kernel0 <<< size_grid, size_block >>>(dev_Input, dev_Kernel, dev_Output);
                            /* Record the end event */
                            CHECK(cudaEventRecord(stop, NULL));
                            /* Wait for the stop event to complete*/
                            CHECK(cudaEventSynchronize(stop));
                            float msec = 0.0f;
                            cudaEventElapsedTime(&msec, start, stop);
                            time_arr[j] = msec;
                        }
                    
                       
                    
                        //cudaError_t err = cudaGetLastError();
                        //if (err != cudaSuccess) printf("Error: %s\n", cudaGetErrorString(err));
                        double msecTotal = 0;
                        for (int j = 1; j < itr; j++) {   
                            printf("%0.5lf\n", time_arr[j]);
                            msecTotal += time_arr[j];
                        }
                    
                        double msecPerMatrixMul = (msecTotal) / itr;
                        double flopsPerMatrixMul = 2.0 * N_B * N_C * N_X * N_Y * N_F * N_R * N_S;
                    
                        double gigaFlops = (flopsPerMatrixMul * 1.0e-9f) / (msecPerMatrixMul / 1000.0f);
                    
                        printf("\n===========================================================\n");
                        printf("Input size: %d X %d X %d X %d\n", N_B, N_C, N_H, N_W);
                        printf("Kernel size: %d X %d X %d X %d\n", N_F, N_C, N_R, N_S);
                        printf("Output size: %d X %d X %d X %d\n", N_B, N_F, N_Y, N_X);
                        printf("flops: %0.5lf\n", (flopsPerMatrixMul * 1.0e-9f));
                        printf("Time is %0.5lf \n", (msecPerMatrixMul / 1000.0f));
                        printf("Gflops %0.5lf \n", gigaFlops);
                        printf("===========================================================\n");
                    
                        /*write back to Host Output -- batch size is 1*/
                        CHECK(cudaMemcpy(Output, dev_Output, sizeof(float) * N_B * N_F * N_X * N_Y, cudaMemcpyDeviceToHost));
                    
                        CHECK(cudaFree(dev_Input));
                        CHECK(cudaFree(dev_Kernel));
                        CHECK(cudaFree(dev_Output));
                    
                    }
            